FREQUENCY_BIN_COUNT = 128
SAMPLE_RATE = 16000

N_FFT = 1024
WINDOW_LENGTH = N_FFT
HOP_LENGTH = WINDOW_LENGTH // 2
MAX_SPECTOGRAM_DURATION_IN_SECONDS = 2.5

#Calculate the max number of samples for the target duration
MAX_SAMPLES = int(MAX_SPECTOGRAM_DURATION_IN_SECONDS * SAMPLE_RATE)

# Calculate the target number of frames for the spectrogram
TARGET_FRAMES = (MAX_SAMPLES - WINDOW_LENGTH) // HOP_LENGTH + 1