"""Test‑bed that walks through the whole RAVDESS directory, applies
basic waveform augmentations from *audio_augmentations.py* to **every**
WAV file it finds, and writes the augmented versions **into the same
Actor_XX folder** as the original.

Usage
-----
$ python test_augmentations.py /path/to/RAVDESS

If you omit the argument, the script assumes the following relative
layout (two levels above this script):
    <project>/data/RAVDESS/

Augmented files are named:
    <original‑stem>_<aug‑name>.wav
and are skipped automatically if they already exist, so you can safely
re‑run the script.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Callable

import librosa
import numpy as np
import soundfile as sf

# --- import your augmentation utilities -------------------------------------
from audio_augmentation import (
    add_background_noise,
    time_stretch,
    pitch_shift,
    change_volume,
    random_crop,
    pad_audio,
    time_mask,
)

###############################################################################
# Configuration helpers
###############################################################################

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_RAVDESS_ROOT = SCRIPT_DIR.parents[1]              # …/ (two levels up)


# Mapping of augmentation name → callable  (each takes (wave, sr) and returns new wave)
AugFunc = Callable[[np.ndarray, int], np.ndarray]

def build_aug_catalog() -> Dict[str, AugFunc]:
    """Return a dict of simple augmentations with *safe* defaults."""
    def _noise(w, sr):
        return add_background_noise(w, noise_factor=0.01)

    def _stretch(w, sr):
        return time_stretch(w, rate=1.1)

    def _pitch(w, sr):
        return pitch_shift(w, sr, n_steps=2)

    def _gain(w, sr):
        return change_volume(w, gain_db=10.0)

    def _crop(w, sr):
        crop_len = max(1, int(len(w) * 0.8))
        return random_crop(w, crop_len)

    def _pad(w, sr):
        target = len(w) + int(sr * 0.5)  # +0.5 s
        return pad_audio(w, target_length=target, mode="random")

    def _timemask(w, sr):
        return time_mask(w, sr, max_mask_sec=0.05, num_masks=2)

    return {
        "noise": _noise,
        "stretch": _stretch,
        "pitch": _pitch,
        "gain": _gain,
        # "crop": _crop,
        # "pad": _pad,
        # "timemask": _timemask,
    }

AUGS = build_aug_catalog()
AUG_SUFFIXES = list(AUGS.keys())

###############################################################################
# Main traversal & processing
###############################################################################

def process_file(wav_path: Path):
    """Load *wav_path*, generate augmented versions, save alongside."""
    # skip files that are *already* augmented (contain _<suffix>.wav)
    stem_lower = wav_path.stem.lower()
    if any(stem_lower.endswith("_" + suf) for suf in AUG_SUFFIXES):
        return  # probably generated by a previous run

    try:
        waveform, sr = librosa.load(wav_path, sr=16000, mono=True)
    except Exception as e:
        print(f"[!] Could not load {wav_path}: {e}")
        return

    for name, func in AUGS.items():
        out_path = wav_path.with_name(f"{wav_path.stem}_{name}.wav")
        # if out_path.exists():
        #     continue  # do not overwrite – idempotent
        try:
            aug_wave = func(waveform, sr)
            sf.write(out_path, aug_wave, sr)
            print("✔", out_path.relative_to(root_dir))
        except Exception as e:
            print(f"[!] Failed {name} on {wav_path.name}: {e}")


def walk_ravdess(root: Path):
    """Recursively process every *.wav under *root*.
    Assumes canonical RAVDESS hierarchy with Actor_XX sub‑dirs."""
    wav_files = sorted(root.rglob("*.wav"))
    if not wav_files:
        print("No WAV files found under", root)
        return
    print(f"Found {len(wav_files)} wav files. Processing…")
    for wav in wav_files:
        process_file(wav)


###############################################################################
# Entrypoint
###############################################################################

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Bulk‑augment RAVDESS wavs in‑place")
    parser.add_argument(
        "root",
        nargs="?",
        type=Path,
        default=DEFAULT_RAVDESS_ROOT,
        help="Path to the RAVDESS directory (defaults to ../../RAVDESS)",
    )
    args = parser.parse_args()

    root_dir = args.root.expanduser().resolve()
    if not root_dir.exists():
        parser.error(f"{root_dir} does not exist")

    walk_ravdess(root_dir)
